flags: {}

resolver: lts-6.16

compiler: ghcjs-0.2.0_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0_ghc-7.10.3:
        url:  https://tolysz.org/ghcjs/lts-6.16-9006016.tar.gz

packages:
- location: '.'
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: c51a5585860db17ce63601524340f09cb75f0129    
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3

    
  
extra-deps:
  - these-0.7.2
  - zenc-0.1.1
  - ref-tf-0.4
  - ghcjs-dom-0.2.3.0
  - string-quote-0.0.1